### ISSUE TITLE
Connecting physical node to Grid hub throws exception in Grid console

### ISSUE THREAD

**Issue by Gytiss** [RationaleEmotions/just-ask#13]
Hello,

It is a great solution when running chrome/firefox using docker. To make this customized Grid more flexible though, an ability to connect physical nodes to the HUB, ie Safari on Mac(phones as well) and IE and Edge for Windows machines is needed.
I connected a physical Win10 machine with IE and Edge browsers. The test passes actually, but Grid Hub console thows exception:
```
java.lang.IllegalStateException: Missing target mapping. Available mappings are {chrome=MappingInfo{browser='chrome',target='selenium/standalone-chrome:latest', implementation='com.rationaleemotions.server.DockerBasedSeleniumServer'}, firefox=MappingInfo{browser='firefox',target='selenium/standalone-firefox-debug:latest', implementation='com.rationaleemotions.server.DockerBasedSeleniumServer'}}
        at com.rationaleemotions.proxy.GhostProxy.beforeCommand(GhostProxy.java:87)
        at org.openqa.grid.internal.TestSession.forward(TestSession.java:222)
        at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:91)
        at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
        at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Unknown Source)
```
Thus it would be nice to run tests targeting physical machines without these errors.
Of course, it is a bit unclear what to do if a physical node is connected with Chrome/Firefox capablities. In that case there should be some logic how to forward requests, probably using platformName. Ie _ANY_, _LINUX_ going to docker.

**Comment by Gytiss** [comment]
From what I see it is just enough not to through exception in:
https://github.com/RationaleEmotions/just-ask/blob/0cd3c5a28425e106bf185a1abb9bef5c9e705854/src/main/java/com/rationaleemotions/proxy/GhostProxy.java#L78

```java
if (type == START_SESSION) {
            try {
                if (processTestSession(session)) {
                    startServerForTestSession(session);
                } else {
                    String msg = "Missing target mapping. Available mappings are " +
                        ConfigReader.getInstance().getMapping();
                    throw new IllegalStateException(msg);
                }
            } catch (Exception e) {
                getRegistry().terminate(session, SessionTerminationReason.CREATIONFAILED);
                LOG.severe("Failed creating a session. Root cause :" + e.getMessage());
                throw e;
            }
        }
```

And this has to be removed from ProxiedTestSlot, to allow default Selenium Grid matching: 
```java
 @Override
    public boolean matches(Map<String, Object> desiredCapabilities) {
        return true;
    }
```
This way there are no exceptions and correct node is selected based on platformName capability.
The added benefit is also the correct icon is dimmed when running Firefox/Chrome, whereas before it would just show that Firefox node is selected when running either running Chrome and Firefox.

**Comment by Gytiss** [comment]
Btw I would more than happy to open a pull request for that if we agree on the above @krmahadevan

**Comment by krmahadevan** [comment]
@gytiss sure thing. Please go ahead and open up a pull request. We can collaborate and get it merged.

**Comment by krmahadevan** [comment]
@Gytiss - If we were to be making `just-ask` to work with a regular proxy as well (which is what gets instantiated when a node wires itself in) then we would need to make more changes than just remove off 

```java
    @Override
    public boolean matches(Map<String, Object> desiredCapabilities) {
        return true;
    }
```

from `com.rationaleemotions.internal.ProxiedTestSlot` because, depending upon which proxy comes up first, there's a good chance that the `GhostProxy` may end up hijacking all requests that are directed at the physical node, since the default capability matching would still be satisfied if you end up wiring in a physical node that matches with the ghost proxy with respect to firefox or chrome as a browser flavor.
